<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AssemblyName>AutoTeam</AssemblyName>
    <RootNamespace>UselessBug.TShockPlugins.AutoTeam</RootNamespace>
    <TShockRoot Condition="'$(TShockRoot)' == ''">$(MSBuildThisFileDirectory)../../tshock-src</TShockRoot>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="$(TShockRoot)/TShockAPI/TShockAPI.csproj" />
  </ItemGroup>
</Project>
